/* Generated by tools/wyrm-tag-import.py and tools/wyrm-tag-append.py. Do not edit. */
#ifndef TAG_COUNT_H
#define TAG_COUNT_H

#define TAG_COUNT 241

/* Wyrm's own tags follow NTL's in the table; their `ntl` is this plus the
   Wyrm tag number (the byte that travels in the skin block's corner). */
#define WYRM_TAG_BASE 100000
#define WYRM_TAG_COUNT 77

#endif
